version: 2.1
orbs:
  ruby: circleci/ruby@1.1

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>
    executor: ruby/default
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec

workflows:
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.7", "3.0"]
